# Generated by Django 2.2.4 on 2022-10-02 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='banner',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='thumbnail',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='watcher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='app_main.User'),
        ),
    ]
